# 1. 라이브러리 불러오기

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [ ]:
train_data = pd.read_csv("/Users/hyunhonoh/Google Drive/My Drive/02. AIFFEL/datathon/sf_Crime_first/Data/train.csv")
test_data = pd.read_csv("/Users/hyunhonoh/Google Drive/My Drive/02. AIFFEL/datathon/sf_Crime_first/Data/test.csv")

# 2. 데이터 분석

## 데이터 설명
1. Category : 범죄 유형 - Target 데이터(test.csv에는 없는 데이터)    
2. Dates : 발생 일자
3. Descript : 범죄 상세 설명 (test.csv에는 없는 데이터)
4. DayOfWeek : 요일
5. PdDistrict : 관할구역(총 10개) 
6. Resolution : 해결여부 (test.csv에는 없는 데이터)
7. Address : 범죄 발생 주소
8. X, Y : 범죄 발생 장소의 경도, 위도

## 2.1 데이터 확인

In [ ]:
train = train_data
test = test_data

In [ ]:
train

,Dates,Category,Descript,DayOfWeek,PdDistrict,Resolution,Address,X,Y
0,2015-05-13 23:53:00,WARRANTS,WARRANT ARREST,Wednesday,NORTHERN,"ARREST, BOOKED",OAK ST / LAGUNA ST,-122.425892,37.774599
1,2015-05-13 23:53:00,OTHER OFFENSES,TRAFFIC VIOLATION ARREST,Wednesday,NORTHERN,"ARREST, BOOKED",OAK ST / LAGUNA ST,-122.425892,37.774599
2,2015-05-13 23:33:00,OTHER OFFENSES,TRAFFIC VIOLATION ARREST,Wednesday,NORTHERN,"ARREST, BOOKED",VANNESS AV / GREENWICH ST,-122.424363,37.800414
3,2015-05-13 23:30:00,LARCENY/THEFT,GRAND THEFT FROM LOCKED AUTO,Wednesday,NORTHERN,NONE,1500 Block of LOMBARD ST,-122.426995,37.800873
4,2015-05-13 23:30:00,LARCENY/THEFT,GRAND THEFT FROM LOCKED AUTO,Wednesday,PARK,NONE,100 Block of BRODERICK ST,-122.438738,37.771541
...,...,...,...,...,...,...,...,...,...
878044,2003-01-06 00:15:00,ROBBERY,ROBBERY ON THE STREET WITH A GUN,Monday,TARAVAL,NONE,FARALLONES ST / CAPITOL AV,-122.459033,37.714056
878045,2003-01-06 00:01:00,LARCENY/THEFT,GRAND THEFT FROM LOCKED AUTO,Monday,INGLESIDE,NONE,600 Block of EDNA ST,-122.447364,37.731948
878046,2003-01-06 00:01:00,LARCENY/THEFT,GRAND THEFT FROM LOCKED AUTO,Monday,SOUTHERN,NONE,5TH ST / FOLSOM ST,-122.403390,37.780266
878047,2003-01-06 00:01:00,VANDALISM,"MALICIOUS MISCHIEF, VANDALISM OF VEHICLES",Monday,SOUTHERN,NONE,TOWNSEND ST / 2ND ST,-122.390531,37.780607
878048,2003-01-06 00:01:00,FORGERY/COUNTERFEITING,"CHECKS, FORGERY (FELONY)",Monday,BAYVIEW,NONE,1800 Block of NEWCOMB AV,-122.394926,37.738212

- 데이터 개수 : 878,049개
- 특징 개수 : 9개

In [ ]:
test

,Id,Dates,DayOfWeek,PdDistrict,Address,X,Y
0,0,2015-05-10 23:59:00,Sunday,BAYVIEW,2000 Block of THOMAS AV,-122.399588,37.735051
1,1,2015-05-10 23:51:00,Sunday,BAYVIEW,3RD ST / REVERE AV,-122.391523,37.732432
2,2,2015-05-10 23:50:00,Sunday,NORTHERN,2000 Block of GOUGH ST,-122.426002,37.792212
3,3,2015-05-10 23:45:00,Sunday,INGLESIDE,4700 Block of MISSION ST,-122.437394,37.721412
4,4,2015-05-10 23:45:00,Sunday,INGLESIDE,4700 Block of MISSION ST,-122.437394,37.721412
...,...,...,...,...,...,...,...
884257,884257,2003-01-01 00:01:00,Wednesday,MISSION,2600 Block of BRYANT ST,-122.408983,37.751987
884258,884258,2003-01-01 00:01:00,Wednesday,NORTHERN,1900 Block of WASHINGTON ST,-122.425342,37.792681
884259,884259,2003-01-01 00:01:00,Wednesday,INGLESIDE,5500 Block of MISSION ST,-122.445418,37.712075
884260,884260,2003-01-01 00:01:00,Wednesday,BAYVIEW,1500 Block of HUDSON AV,-122.387394,37.739479
884261,884261,2003-01-01 00:01:00,Wednesday,TARAVAL,1500 Block of SLOAT BL,-122.489714,37.733950

- 데이터 개수 : 884,262개
- 특징 개수 : 7개

In [ ]:
# 범죄 위치에 대한 기술통계량 확인
train.describe()

                   X              Y
count  878049.000000  878049.000000
mean     -122.422616      37.771020
std         0.030354       0.456893
min      -122.513642      37.707879
25%      -122.432952      37.752427
50%      -122.416420      37.775421
75%      -122.406959      37.784369
max      -120.500000      90.000000

범죄 평균 위치
![image.png](attachment:4837bc74-e43e-4523-89c8-a6cbed7dd654.png)

In [ ]:
train.columns

Index(['Dates', 'Category', 'Descript', 'DayOfWeek', 'PdDistrict',
       'Resolution', 'Address', 'X', 'Y'],
      dtype='object')

In [ ]:
test.columns

Index(['Id', 'Dates', 'DayOfWeek', 'PdDistrict', 'Address', 'X', 'Y'], dtype='object')

In [ ]:
# Category 유형
Category = train['Category'].unique()
print('Category 개수 :', len(Category))
Category

Category 개수 : 39

array(['WARRANTS', 'OTHER OFFENSES', 'LARCENY/THEFT', 'VEHICLE THEFT',
       'VANDALISM', 'NON-CRIMINAL', 'ROBBERY', 'ASSAULT', 'WEAPON LAWS',
       'BURGLARY', 'SUSPICIOUS OCC', 'DRUNKENNESS',
       'FORGERY/COUNTERFEITING', 'DRUG/NARCOTIC', 'STOLEN PROPERTY',
       'SECONDARY CODES', 'TRESPASS', 'MISSING PERSON', 'FRAUD',
       'KIDNAPPING', 'RUNAWAY', 'DRIVING UNDER THE INFLUENCE',
       'SEX OFFENSES FORCIBLE', 'PROSTITUTION', 'DISORDERLY CONDUCT',
       'ARSON', 'FAMILY OFFENSES', 'LIQUOR LAWS', 'BRIBERY',
       'EMBEZZLEMENT', 'SUICIDE', 'LOITERING',
       'SEX OFFENSES NON FORCIBLE', 'EXTORTION', 'GAMBLING', 'BAD CHECKS',
       'TREA', 'RECOVERED VEHICLE', 'PORNOGRAPHY/OBSCENE MAT'],
      dtype=object)

In [ ]:
# 중복값 확인
test.duplicated().sum()            # test 데이터셋은 중복값 없음

train.duplicated().sum()

2323

In [ ]:
# 중복값 제거
train = train_data.drop_duplicates().reset_index(drop=True)
train.head()

,Dates,Category,Descript,DayOfWeek,PdDistrict,Resolution,Address,X,Y
0,2015-05-13 23:53:00,WARRANTS,WARRANT ARREST,Wednesday,NORTHERN,"ARREST, BOOKED",OAK ST / LAGUNA ST,-122.425892,37.774599
1,2015-05-13 23:53:00,OTHER OFFENSES,TRAFFIC VIOLATION ARREST,Wednesday,NORTHERN,"ARREST, BOOKED",OAK ST / LAGUNA ST,-122.425892,37.774599
2,2015-05-13 23:33:00,OTHER OFFENSES,TRAFFIC VIOLATION ARREST,Wednesday,NORTHERN,"ARREST, BOOKED",VANNESS AV / GREENWICH ST,-122.424363,37.800414
3,2015-05-13 23:30:00,LARCENY/THEFT,GRAND THEFT FROM LOCKED AUTO,Wednesday,NORTHERN,NONE,1500 Block of LOMBARD ST,-122.426995,37.800873
4,2015-05-13 23:30:00,LARCENY/THEFT,GRAND THEFT FROM LOCKED AUTO,Wednesday,PARK,NONE,100 Block of BRODERICK ST,-122.438738,37.771541

In [ ]:
# 결측치 확인
train.isnull().sum()                    # 결측치 없음   
# test.isnull().sum()                   # 결측치 없음

Dates         0
Category      0
Descript      0
DayOfWeek     0
PdDistrict    0
Resolution    0
Address       0
X             0
Y             0
dtype: int64

In [ ]:
# 컬럼별 데이터 타입 확인
train.dtypes

Dates          object
Category       object
Descript       object
DayOfWeek      object
PdDistrict     object
Resolution     object
Address        object
X             float64
Y             float64
dtype: object

- Dates 컬럼 데이터 타입은 문자열이므로 datetime 형으로 변환
- 필요한 년, 월, 일, 시, 분, 초 추출 후 새로운 컬럼으로 추가

In [ ]:
# datetime으로 변경하는 함수 정의
def to_datetime(data):
    data['Dates'] = pd.to_datetime(data['Dates'])
    
    data['year'] = data['Dates'].dt.year.astype(np.uint16)
    data['month'] = data['Dates'].dt.month.astype(np.uint8)
    data['day'] = data['Dates'].dt.day.astype(np.uint8)
    data['hour'] = data['Dates'].dt.hour.astype(np.uint8)
    data['minute'] = data['Dates'].dt.minute.astype(np.uint8)
    data['second'] = data['Dates'].dt.second.astype(np.uint8)
    
    return data

In [ ]:
# 날짜 데이터 datetimes64 타입으로 변경
train = to_datetime(train)
test = to_datetime(test)

In [ ]:
# datetime으로 변경됐는지 확인
train.dtypes
# test.dtypes

Dates         datetime64[ns]
Category              object
Descript              object
DayOfWeek             object
PdDistrict            object
Resolution            object
Address               object
X                    float64
Y                    float64
year                  uint16
month                  uint8
day                    uint8
hour                   uint8
minute                 uint8
second                 uint8
dtype: object

In [ ]:
# train 데이터셋 주말, 평일 추출 함수 정의
def weekday_weekend(data):
    # 방법1
    # data['weekday'] = [np.uint8(1) if (day == 'Saturday')|(day == 'Sunday') else np.uint(0) for day in data['DayOfWeek']]

    # 방법2
    # data['weekday'] = np.where((data['DayOfWeek'] == 'Saturday')|(data['DayOfWeek'] == 'Sunday'), 1, 0)

    # 방법3
    data['weekday'] = data['DayOfWeek'].apply(lambda x : 1 if x == 'Saturday' or x =='Sunday' else 0)
    data.head()
    
    return data

In [ ]:
# train 데이터셋 주말, 평일 추출후 컬럼 옆에 추가하기
train = weekday_weekend(train)
test = weekday_weekend(test)

In [ ]:
# 계절 컬럼 추가하는 함수 정의
def season(m):
  if 3 <= m <= 5:
    season = 'spring'
  elif 6 <= m <=8:
    season = 'summer'
  elif 9 <= m <= 11:
    season = 'fall'
  else:
    season = 'winter'

  return season

In [ ]:
# 계절 컬럼 추가하기
train['season'] = train['month'].apply(season)
test['season'] = test['month'].apply(season)

In [ ]:
# 계절 추가된지 확인하기
train['season'].unique()

array(['spring', 'winter', 'fall', 'summer'], dtype=object)

### 이상치 제거
- 샌프란시스코에서 벗어난 위도 경도 좌표 제거
- EDA 시각화하면서 발견하면 이상치 제거하겠음

In [ ]:
# 2015년 5월까지 있는지 확인
a = train[(train['year'] == 2015) & (train['month'] < 13)]
a['month'].max()

5

array([37.7745986 , 37.80041432, 37.80087263, ..., 37.77644744,
       37.73394539, 37.73821154])

In [ ]:
# 파일 저장하기
train.to_csv('/Users/hyunhonoh/MyDeveloper/Aiffel/datathon/1. SF_Crime/Data/train_preprocessed.csv', index=False)      # index 없이 저장함
test.to_csv('/Users/hyunhonoh/MyDeveloper/Aiffel/datathon/1. SF_Crime/Data/test_preprocessed.csv', index=False)        # index 없이 저장함